const VITE_APP_API_URL = import.meta.env.VITE_APP_API_URL ?? 'http://localhost:5051'
const VITE_APP_RECAPTCHA_SITE_KEY = import.meta.env.VITE_APP_RECAPTCHA_SITE_KEY ?? ''
const VITE_APP_SESSION = import.meta.env.VITE_APP_SESSION ?? 'RCTSESSION'
const VITE_APP_NODE_ENV = import.meta.env.VITE_APP_NODE_ENV ?? 'development'
const VITE_APP_SENTRY_DNS = import.meta.env.VITE_APP_SENTRY_DNS ?? ''
const VITE_APP_GOOGLE_ANALYTICS = import.meta.env.VITE_APP_GOOGLE_ANALYTICS ?? ''
const VITE_APP_GOOGLE_MAP = import.meta.env.VITE_APP_GOOGLE_MAP ?? ''
const VITE_APP_GOOGLE_OAUTH_CLIENT_ID = import.meta.env.VITE_APP_GOOGLE_OAUTH_CLIENT_ID ?? ''
const VITE_APP_FIREBASE_API_KEY = import.meta.env.VITE_APP_FIREBASE_API_KEY ?? ''
const VITE_APP_FIREBASE_AUTH_DOMAIN = import.meta.env.VITE_APP_FIREBASE_AUTH_DOMAIN ?? ''
const VITE_APP_FIREBASE_PROJECT_ID = import.meta.env.VITE_APP_FIREBASE_PROJECT_ID ?? ''
const VITE_APP_FIREBASE_STORAGE_BUCKET = import.meta.env.VITE_APP_FIREBASE_STORAGE_BUCKET ?? ''
const VITE_APP_FIREBASE_MESSAGING_SENDER_ID =
    import.meta.env.VITE_APP_FIREBASE_MESSAGING_SENDER_ID ?? ''
const VITE_APP_FIREBASE_APP_ID = import.meta.env.VITE_APP_FIREBASE_APP_ID ?? ''
const VITE_APP_FIREBASE_MEASUREMENT_ID = import.meta.env.VITE_APP_FIREBASE_MEASUREMENT_ID ?? ''

export {
    VITE_APP_API_URL,
    VITE_APP_RECAPTCHA_SITE_KEY,
    VITE_APP_SESSION,
    VITE_APP_NODE_ENV,
    VITE_APP_SENTRY_DNS,
    VITE_APP_GOOGLE_ANALYTICS,
    VITE_APP_GOOGLE_MAP,
    VITE_APP_GOOGLE_OAUTH_CLIENT_ID,
    VITE_APP_FIREBASE_API_KEY,
    VITE_APP_FIREBASE_AUTH_DOMAIN,
    VITE_APP_FIREBASE_PROJECT_ID,
    VITE_APP_FIREBASE_STORAGE_BUCKET,
    VITE_APP_FIREBASE_MESSAGING_SENDER_ID,
    VITE_APP_FIREBASE_APP_ID,
    VITE_APP_FIREBASE_MEASUREMENT_ID,
}

// '50 impala
