import dotenv from 'dotenv'
dotenv.config()
const MONGO_URL = process.env.MONGO_URL ?? ''
const MONGO_DB = process.env.MONGO_DB ?? 'core1'

const NODE_ENV = process.env.NODE_ENV ?? 'development'
const EXPRESS_PORT = process.env.EXPRESS_PORT ?? 5051
const REACT_APP_ORIGIN = process.env.REACT_APP_ORIGIN ?? 'http://localhost:3000'
const RECAPTCHA_SECRET = process.env.RECAPTCHA_SECRET ?? ''

const GOOGLE_OAUTH_CLIENT_ID = process.env.GOOGLE_OAUTH_CLIENT_ID ?? ''
const GOOGLE_OAUTH_SECRET_ID = process.env.GOOGLE_OAUTH_SECRET_ID ?? ''
const GITHUB_OAUTH_CLIENT_ID = process.env.GITHUB_OAUTH_CLIENT_ID ?? ''
const GITHUB_OAUTH_SECRET_ID = process.env.GITHUB_OAUTH_SECRET_ID ?? ''

const API_RATE_LIMIT = process.env.API_RATE_LIMIT ?? 30
const API_RATE_DELAY = process.env.API_RATE_DELAY ?? 600
const API_EXTERNAL_RATE_LIMIT = process.env.API_EXTERNAL_RATE_LIMIT ?? 1000
const API_EXTERNAL_RATE_DELAY = process.env.API_EXTERNAL_RATE_DELAY ?? 600

const MAIL_HOST = process.env.MAIL_HOST ?? 'smtp.gmail.com'
const MAIL_PORT = process.env.MAIL_HOST ?? 587
const MAIL_USERNAME = process.env.MAIL_USERNAME ?? ''
const MAIL_PASSWORD = process.env.MAIL_PASSWORD ?? ''
const MAIL_FROM_ADDRESS = process.env.MAIL_FROM_ADDRESS ?? ''

const GITHUB_AUTH_TOKEN = process.env.GITHUB_AUTH_TOKEN ?? ''
const GITHUB_REPO = process.env.GITHUB_REPO ?? 'core1'
const GITHUB_OWNER = process.env.GITHUB_OWNER ?? 'freight-capstone'

const SENTRY_DNS = process.env.SENTRY_DNS ?? ''
const SENTRY_AUTH_TOKEN = process.env.SENTRY_AUTH_TOKEN ?? ''
const SENTRY_ORGANIZATION_SLUG = process.env.SENTRY_ORGANIZATION_SLUG ?? 'freight-capstone'
const SENTRY_PROJECT_SLUG = process.env.SENTRY_PROJECT_SLUG ?? 'core1'

const GEMINI_AUTH_KEY_DKCE = process.env.GEMINI_AUTH_KEY_DKCE ?? ''
const GEMINI_AUTH_KEY_GRQA = process.env.GEMINI_AUTH_KEY_GRQA ?? ''
const GEMINI_AUTH_KEY_J5E0 = process.env.GEMINI_AUTH_KEY_J5E0 ?? ''
const GEMINI_AUTH_KEY_RMYU = process.env.GEMINI_AUTH_KEY_RMYU ?? ''
const GEMINI_AUTH_KEY_LH0Q = process.env.GEMINI_AUTH_KEY_LH0Q ?? ''
const GEMINI_AUTH_KEY_QQXS = process.env.GEMINI_AUTH_KEY_QQXS ?? ''
const GEMINI_AUTH_KEY_VPTQ = process.env.GEMINI_AUTH_KEY_VPTQ ?? ''
const GEMINI_AUTH_KEY_N3SU = process.env.GEMINI_AUTH_KEY_N3SU ?? ''
const GEMINI_AUTH_KEY_THIS = process.env.GEMINI_AUTH_KEY_THIS ?? ''
const GEMINI_AUTH_KEY_333K = process.env.GEMINI_AUTH_KEY_333K ?? ''
const GEMINI_AUTH_KEY_CMPS = process.env.GEMINI_AUTH_KEY_CMPS ?? ''
const GEMINI_AUTH_KEY_RJGG = process.env.GEMINI_AUTH_KEY_RJGG ?? ''

export {
    MONGO_URL,
    MONGO_DB,
    NODE_ENV,
    EXPRESS_PORT,
    REACT_APP_ORIGIN,
    RECAPTCHA_SECRET,
    GOOGLE_OAUTH_CLIENT_ID,
    GOOGLE_OAUTH_SECRET_ID,
    GITHUB_OAUTH_CLIENT_ID,
    GITHUB_OAUTH_SECRET_ID,
    API_RATE_LIMIT,
    API_RATE_DELAY,
    API_EXTERNAL_RATE_LIMIT,
    API_EXTERNAL_RATE_DELAY,
    MAIL_HOST,
    MAIL_PORT,
    MAIL_USERNAME,
    MAIL_PASSWORD,
    MAIL_FROM_ADDRESS,
    GITHUB_AUTH_TOKEN,
    GITHUB_REPO,
    GITHUB_OWNER,
    SENTRY_DNS,
    SENTRY_AUTH_TOKEN,
    SENTRY_ORGANIZATION_SLUG,
    SENTRY_PROJECT_SLUG,
    GEMINI_AUTH_KEY_DKCE,
    GEMINI_AUTH_KEY_GRQA,
    GEMINI_AUTH_KEY_J5E0,
    GEMINI_AUTH_KEY_RMYU,
    GEMINI_AUTH_KEY_LH0Q,
    GEMINI_AUTH_KEY_QQXS,
    GEMINI_AUTH_KEY_VPTQ,
    GEMINI_AUTH_KEY_N3SU,
    GEMINI_AUTH_KEY_THIS,
    GEMINI_AUTH_KEY_333K,
    GEMINI_AUTH_KEY_CMPS,
    GEMINI_AUTH_KEY_RJGG,
}
