name: Docker CI

on:
  push:
    branches: ["core1-backend"]
  workflow_call:
  workflow_dispatch:

jobs:
  docker:
    runs-on: 'ubuntu-latest'
    if: github.repository == 'axleshift/core1'
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: core1-backend

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.APP_DOCKER_USERNAME }}
          password: ${{ secrets.APP_DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t mrepol742/core1-server:latest .

      - name: Push Docker image
        run: |
          docker push mrepol742/core1-server:latest

      - name: Run Docker container
        run: |
          docker run -d -p 5051:5051 --name core1-server mrepol742/core1-server:latest

      - name: Check container logs
        run: |
          docker logs core1-server

      - name: Stop and remove container
        if: always()
        run: |
          docker stop core1-server
          docker rm core1-server
