name: Greetings

on: 
  pull_request_target: 
  issues:

jobs:
  greetings:
  
    runs-on: 'ubuntu-latest'
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.API_TOKEN_GITHUB }}
          issue-message: |
            Welcome to the Project!

            Thank you for opening your first issue! We appreciate your input and are excited to hear your thoughts. Your feedback helps us improve and enhance the project.

            If you have any questions or need assistance, don't hesitate to reach out. We're here to help!

            Happy contributing!

          pr-message: |
            Great to See Your First Pull Request!

            Thank you for submitting your first pull request! We're thrilled to see your contributions and can't wait to review your work. Your efforts are crucial to the success of our project.

            If you have any questions during the review process, please let us know. We're here to support you!

            Happy coding!
